fhi/fhi/urls.py
from django.contrib import admin
from django.urls import include, path

urlpatterns = [
    path('admin/', admin.site.urls),
    path('', include('map.urls'))
]

fhi/map/urls.py
from django.urls import path

from . import views

urlpatterns = [
    path('', views.map, name='map'),
    path('plants/',views.plants, name='plants'),
]

fhi/map/models.py
from django.db import models
from django.forms import ModelForm
import os

# Create your models here.
class Waypoint(models.Model):
    long = models.FloatField()
    lat = models.FloatField()
    area = models.ForeignKey('Area', on_delete=models.CASCADE, blank=True, null=True)
    plant = models.ForeignKey('PlantType', on_delete=models.CASCADE, blank=True, null=True)


class Area(models.Model):
    name = models.CharField(max_length=25)
    class Meta:
        verbose_name_plural = "Areas"
    def __str__(self):
        return self.name

class PlantType(models.Model):
    marker_dir = os.path.join(os.getcwd(),"fhi/map/static/marker")
    colors = []
    for marker in os.listdir(marker_dir):
        if marker.startswith("marker-icon-") and os.path.isfile(os.path.join(marker_dir, marker)):
            color = marker.split("-")[2].replace(".png","")
            colors.append((color,color.upper()))

    name = models.CharField(max_length=25)
    lat_name = models.CharField(max_length=50, blank=True, null=True)
    wiki = models.CharField(max_length=50, blank=True, null=True)
    description = models.TextField(blank=True, null=True)
    short_description = models.CharField(max_length=50,blank=True, null=True)
    marker_color = models.CharField(choices=colors, max_length=10, blank=True, null=True)
    class Meta:
        verbose_name_plural = "PlantTypes"
    def __str__(self):
        return self.name


class WaypointForm(ModelForm):
    class Meta:
        model = Waypoint
        fields = ['long', 'lat', 'plant', 'area']

fhi/map/views.py
from django.shortcuts import render
from django.core import serializers
from django.http import HttpResponse
from django.template import loader
from django.db.models import Max
from json import dumps

from .models import Waypoint, Area, PlantType, WaypointForm

def index(request):
    return HttpResponse("Hello, world. You're at the map index.")


def map(request):
    if request.method == "POST":
        form = WaypointForm(request.POST)
        print(request.POST)
        if form.is_valid():
            form.save()
    focus_plants = ""
    edit = False
    try:
        uri,query = request.get_full_path().split("?")
        params = query.split(",")
        for param in params:
            try:
                key,value = param.split("=")
                if key == "display" and value:
                    focus_plants+=(str(value))+","
            except:
                if param == "edit":
                    edit = True
    except:
        noQuery = True
    area_points = Waypoint.objects.filter(area__isnull=False)
    plants = Waypoint.objects.filter(plant__isnull=False).select_related('plant')
    template = loader.get_template('map/map.html')
    plantlist = []
    for plant in plants:
        new_plant = {
            'type': str(plant.plant.pk),
            'name': str(plant.plant.name),
            'color': str(plant.plant.marker_color),
            'lat': plant.lat,
            'long': plant.long
        }
        plantlist.append(new_plant)

    context = {
        'max_area_id': Area.objects.filter().aggregate(Max('pk')).get("pk__max"),
        'max_planttype_id': PlantType.objects.filter().aggregate(Max('pk')).get("pk__max"),
        'area_list': serializers.serialize('json', area_points),
        'plant_list': dumps(plantlist),
        'focus_plants': str(focus_plants),
        'newPlantForm': WaypointForm(),
        'edit_mode': str(edit),
    }
    return HttpResponse(template.render(context, request))

def plants(request):
    focus_cards=""
    try:
        uri,query = request.get_full_path().split("?")
        params = query.split(",")
        for param in params:
            try:
                key,value = param.split("=")
                if key == "name" and value:
                    focus_cards+=(str(value))+","
            except:
                error = True
    except:
        noQuery = True
    template = loader.get_template('map/plants.html')
    context = {
        'plant_types': PlantType.objects.all(),
        'focus_cards': str(focus_cards),
    }
    return HttpResponse(template.render(context, request))

fhi/map/templates/map/base.html
{% load static %}
<!doctype html>
<html lang="en">
  <head>
    <meta charset="utf-8">
    <meta name="viewport" content="width=device-width, initial-scale=1, shrink-to-fit=no">
    <link rel="stylesheet" type="text/css" href="{% static '/css/bootstrap.min.css' %}" >
    <link rel="stylesheet" type="text/css" href="{% static '/css/style.css' %}" />
  </head>
  <body>
    <script src="{% static '/js/focuscontrol.js' %}"></script>
    <div class="container-md wrapper">
      <div class="col-md-auto">
        <!-- Navigationbar -->
        <nav class="navbar navbar-expand-md">
          <button class="navbar-toggler" type="button" data-toggle="collapse" data-target="#navbarNav" aria-controls="navbarNav" aria-expanded="false" aria-label="Toggle navigation">
            <span class="navbar-toggler-icon"></span>
          </button>
          <div class="collapse navbar-collapse" id="navbarNav">
            <ul class="navbar-nav mr-auto">
              <li><a class="nav-item nav-link tab_focused navbar-nav" id="tab_map" href="/">FHI-Nutzpflanzenkarte</a></li>
              <li><a class="nav-item nav-link tab_background navbar-nav" id="tab_plant" href="/plants">Pflanzen</a></li>
            </ul>
          </div>
        </nav>
        <!--Contentblock-->
        <div id="content", name="content", class="content wrapper">
            <div class="row justify-content-center marged">
                {% block content %}
                {% endblock %}
            </div>
        </div>
        <!-- Footer block -->
        <footer class="mt-auto row footer marged">
          <div class="column col-sm-6" style="text-align: left;">
            <a class="invisble" href="/">Nutzpflanzenkarte</a></br>
            <a class="invisble" href="/plants">Pflanzenübersicht</a>
          </div>
          <div class="column col-sm-6" style="text-align: right;">
            Copyright © 2021 Marcel Endres</br>
            <a class="invisble" href="https://github.com/mdotend/FHI_Campusmap">Code on Github</a>
          </div>
        </footer>
      </div>
    </div>
    <!-- import required js scripts for bootstrap -->
    <script src="{% static '/js/jquery-3.5.1.min.js' %}"></script>
    <script src="{% static '/js/bootstrap.min.js' %}"></script>
    <script src="{% static '/js/popper.min.js' %}"></script>
  </body>
</html>

fhi/map/templates/map/map.html
{% extends './base.html' %}
{% load icons %}
{% load static %}
{% block content %}
{% load leaflet_tags %}

<script>
    window.addEventListener("map:init", function (e) {
        var map = e.detail.map;  
        
        var area_points = "{{ area_list }}";
        area_points = JSON.parse(area_points.replace(/&quot;/ig,'"')); //import and transform json
        if (area_points){
            for ( var i = 0; i<="{{ max_area_id }}"; i++){
                poly = [];
                area_points.forEach(waypoint => {
                    if (waypoint.fields.area == i){
                        poly.push([waypoint.fields.lat,waypoint.fields.long])
                    }
                });
                L.polygon(poly, {color: "#006C66", weight: 1.5,fillOpacity: 0.1}).addTo(map);
            }
        }
        var plant_points = "{{ plant_list }}";
        plant_points = JSON.parse(plant_points.replace(/&quot;/ig,'"'));
        var control = L.control.layers({}, {}, {"collapsed": false});
        if (plant_points){
            for ( var i = 0; i<="{{ max_planttype_id }}"; i++){
                group = [];
                plant_name = "";
                plant_points.forEach(plant => {
                    if (plant.type == i){
                        var customIcon = new L.Icon({
                            iconUrl: `/static/marker/marker-icon-${plant.color}.png`,
                            shadowUrl: '/static/marker/marker-shadow.png',
                            iconSize: [25, 41],
                            iconAnchor: [12, 41],
                            popupAnchor: [1, -34],
                            shadowSize: [41, 41]
                        });
                        var marker = new L.marker([plant.lat,plant.long], {icon: customIcon});
                        group.push(marker);
                        marker.bindPopup(`<a href="plants/?name=${plant.name}" class="btn btn-primary marged" style="color: white;">${plant.name}</a>`, {closeButton: true});
                        plant_name = plant.name;
                    }
                });
                if(group.length > 0 && plant_name != ""){
                    plantGroup = L.layerGroup(group);
                    if ("{{ focus_plants }}".search(plant_name) != -1 || "{{ focus_plants }}" == []){
                        plantGroup.addTo(map);
                    }
                    control.addOverlay(plantGroup, plant_name);
                }
            }
        }
        control.addTo(map);
        if ('{{ edit_mode }}' == "True"){
            L.easyButton('<b>X</b>', function(){
                window.open("/", "_self");
            }).addTo(map);
            
            map.on('click', function(e) {
                var marker = new L.marker([e.latlng.lat, e.latlng.lng], {draggable:true});
                updatePopup(marker);
                marker.addTo(map);

                marker.on('dragend', function (e) {
                    updatePopup(marker);
                });
            });  
            function updatePopup(marker) {
                marker.bindPopup(`<form action="" method="post">{% csrf_token %}{{ newPlantForm.non_field_errors }}
                                <div class="fieldWrapper">
                                    {{ newPlantForm.lat.errors }}
                                    <input type="hidden" name="lat" step="any" required="" id="id_lat" value=${marker.getLatLng().lat}>
                                </div>
                                <div class="fieldWrapper">
                                    {{ newPlantForm.long.errors }}
                                    <input type="hidden" name="long" step="any" required="" id="id_long" value=${marker.getLatLng().lng}>

                                </div>
                                <div class="fieldWrapper">
                                    {{ newPlantForm.plant.error }}
                                    <label for="id_plant">Pflanze</label> {{ newPlantForm.plant }}
                                </div>
                                <div class="fieldWrapper">
                                    {{ newPlantForm.area.error }}
                                    <label for="id_area">Gebiet</label> {{ newPlantForm.area }}
                                </div>
                                <input type="submit" value="Hinzufügen" class="btn btn-primary"/>
                            </form>`, 
                            {closeButton: true}
                );
            }
        }
        else{
            L.easyButton('<img src="../static/icons/Edit_icon_(the_Noun_Project_30184).svg" width="130%">', function(){
                window.open("/?edit", "_self");
            }).addTo(map);
        }
    }, false);
</script>

<head>
    {% leaflet_js %}
    {% leaflet_css %}
    <link rel="stylesheet" href="{% static '/css/easybutton.css' %}">
    <title>FHI Nutzpflanzenkarte</title>
</head>

<body>
    <script src="{% static '/js/easybutton.js' %}"></script>    
    <script>changeActiveTab("tab_map")</script>
    {% leaflet_map "map"%}
</body>
{% endblock %}

fhi/map/templates/map/plants.html
{% extends './base.html' %}
{% block content %}
<head>
  <title>Pflanzenübersicht</title>
</head>
<body>
  <script>changeActiveTab("tab_plant")</script>
  {% load static %}
  <h1> Diese Nutzpflanzen sind auf dem FHI Campus zu finden</h1>
  <br>
  <div class="container">
      <div class="row gy-5">
          {% for plant in plant_types %}
              <div class="col-sm gx-5">
                  <div class="card mb-2" id="{{ plant.name }}-card">
                      <img class="card-img-top" src="{% static 'plants/' %}{{ plant.name }}.jpg" alt="Card image cap">
                      <div class="card-body">
                        <h5 class="card-title">{{ plant.name }}</h5>
                        <p class="card-text">{{ plant.short_description }}</p>
                        <div class="row justify-content-center marged">
                          <a href="../?display={{ plant.name }}" class="btn btn-primary marged">zur Karte</a>
                          <a href="{{ plant.wiki }}"><img style="width:50px;"src="https://upload.wikimedia.org/wikipedia/en/thumb/8/80/Wikipedia-logo-v2.svg/1200px-Wikipedia-logo-v2.svg.png" alt="Wikipedia-logo-v2.svg"></a>
                        </div>
                      </div>
                  </div>
              </div>
          {% endfor %}
      </div>
    </div>
</body>
<script>setActiveCard("{{ focus_cards }}")</script>
{% endblock %}